### ISSUE TITLE
Could not pull from zkillboard

### ISSUE THREAD

**Issue by Bingmano** [jalavoy/slack-kbbot#1]
keep getting this message, all the information is correct in the conf file from what i can tell.  not sure how to proceed.

**Comment by jalavoy** [comment]
That error occurs if the response it gets back from zkillboard isn't valid. It's just making a normal http request out, so maybe there is an outbound firewall blocking the connection?

I added some debug output to that particular function, if you wanna pull down a new copy and run it with the -d flag it should dump out some better information.

**Comment by Bingmano** [comment]
excellent!  fixed my problem, didn't have the LWP::Protocol::https package installed.

**Comment by jalavoy** [comment]
Huzzah!
